# Composition of two crisp relations

Given R is a relation on X,Y and S is another relation on Y,Z.
<br>Then **R◦S is called a composition of relation** on X and Z which is defined as follows: 
### R◦S = {(x,z)|(x,y) ∈ R and(y,z) ∈ S and ∀ y ∈ Y}

#### Max-Min Composition:
#### T(x,z) =max{min{ R(x,y) , S(y,z) and ∀ y ∈ Y}}

In [1]:
x = {1,3,5}
y = {1,3,5}

In [2]:
r = set()
s = set()
for i in x:
    for j in y:
        if(j==i+2):
            r.add((i,j))
            
        if(i<j):
            s.add((i,j))

In [3]:
s

{(1, 3), (1, 5), (3, 5)}

In [3]:
r

{(1, 3), (3, 5)}

Allocate memory for matrix!

In [4]:
import numpy as np
r_matrix = np.zeros((len(x),len(y)))
s_matrix = np.zeros((len(x),len(y)))
s_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
temp_unique = []
for i in r:
    temp_unique.append(i[0])
    temp_unique.append(i[1])

List with unique elements is created in order to avoid **index out of bounds error** in following loops

In [6]:
temp_unique = list(set(temp_unique))
temp_unique

[1, 3, 5]

R and S Matrix are initialized with proper values.

In [7]:
for i in r:
    row = temp_unique.index(i[0])
    col = temp_unique.index(i[1])
    r_matrix[row][col] = 1
    
for i in s:
    row = temp_unique.index(i[0])
    col = temp_unique.index(i[1])
    s_matrix[row][col] = 1

In [8]:
r_matrix

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
s_matrix

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
t_matrix = np.zeros(((len(x),len(y))))
t_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
for i in range(len(s_matrix[0])):
    for j in range(len(r_matrix[0]) - 1):
        for k in range(len(t_matrix[0])):
            t_matrix[i][k] = max(min(r_matrix[i][j], s_matrix[j][k]), 
                                 min(r_matrix[i][j+1], s_matrix[j+1][k]))

#### T(x,z) =max{min{ R(x,y) , S(y,z) and ∀ y ∈ Y}}
Final T Matrix

In [12]:
t_matrix

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])