# Composition of two fuzzy relations

In [10]:
import numpy as np

## Import Fuzzy Membership Values from CSV file as Matrix

In [2]:
mat1 = np.genfromtxt("matrix.csv", delimiter=",")
mat2 = np.genfromtxt("matrix2.csv", delimiter=",")

In [3]:
mat1

array([[0.5, 0.1],
       [0.2, 0.9],
       [0.8, 0.6]])

In [11]:
mat2

array([[0.6, 0.4, 0.7],
       [0.5, 0.8, 0.9]])

## Measure Matrix Length for Generalization of Program

In [4]:
mat1_row = len(mat1)
mat1_col = len(mat1[0])

mat2_row = len(mat2)
mat2_col = len(mat2[0])

## Allocate Memory for Answer Matrix

In [5]:
mat3 = np.zeros((mat1_row,mat2_col))
mat3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Perform RoS Operation

In [6]:
for i in range(mat1_row):
    for j in range(mat1_col - 1):
        for k in range(mat2_col):
            mat3[i][k] = max(min(mat1[i][j], mat2[j][k]), min(mat1[i][j+1], mat2[j+1][k]))

## Store RoS Operation to Answer Matrix

In [13]:
mat3

array([[0.5, 0.4, 0.5],
       [0.5, 0.8, 0.9],
       [0.6, 0.6, 0.7]])